name = "cron" # 你的 Worker 名字，会成为 URL 的一部分
main = "worker.js"      # 入口文件，请将下载的代码命名为 index.js
compatibility_date = "2023-10-30"

# 绑定刚才创建的 KV，如果手动在worker中绑定这个配置可以注释掉
[[kv_namespaces]]
binding = "KEEP_ALIVE_DB"         # 这个名字必须和代码中的 env.KEEP_ALIVE_DB 保持一致
id = "51bb1f4259e546669f8203e420e22043" # 粘贴你上一步获取的 ID

# 配置定时任务，每天执行一次
[triggers]
crons = ["* * * * *"] # 必选都是*，不然无法定时到某个时间点发送提醒

# [vars]
# 这里可以放非敏感信息，但为了统一管理，我们推荐使用 secrets

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./public"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application" #不存在静态资源时返回index.html

# 如果设为 false (默认值)：Cloudflare 会先看 dist 文件夹里有没有对应的文件。如果有（比如 logo.png），直接返回文件，不运行你的 JS 代码。
# 如果设为 true：每一个请求（无论是图片、HTML 还是 API）都会先进入你的 Worker JS 逻辑。
run_worker_first = true

# [build]
# command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"